#!/usr/bin/python3
# -*- coding: utf-8 -*-
# AoC_TAG 
# generated by Structorizer 3.32-11 

# Copyright (C) 2022-12-04 stefa 

from enum import Enum
import math

def einlesen(debug) :
    if (debug):
        dateiname = "test.txt"
    else:
        dateiname = "input.txt"

    dateinummer = fileOpen(dateiname)
    if (dateinummer > 0):
        zaehler = 0
        while (not  fileEOF(dateinummer)):
            tempzeile = fileReadLine(dateinummer)
            tempwert[zaehler] = tempzeile
            zaehler = zaehler +1

        einlesen = tempwert
    else:
        einlesen = []

    return einlesen

# Wenn debug dann test.txt öffnen sonst input.txt 
debug = true
# Inputdatei einlesen 
liste = einlesen(debug)
# Wenn keine Elemente eingelesen wurden abbrechen 
if (length(liste) == 0):
    return 

# Importierte Date liegt zeilenweise vor und wird durchlaufen 
for i in range(0, length(liste)-1+1, 1):
